name: Generate Snake Animation

on:
  # Run automatically every 12 hours
  schedule:
    - cron: "0 */12 * * *"
  
  # Also run on every push to the main branch
  push:
    branches:
      - main
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Check out the repository so the workflow can access it
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Generate the snake animation files
      - name: Generate snake animation
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: UnityNimit
          # The output files, which will be created in a 'dist' directory
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # Step 3: Commit and push the generated files back to the repository
      - name: Commit and push snake animation
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: update snake animation"
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
          # The specific files to commit. This prevents other files from being touched.
          file_pattern: dist/*.svg