name: Update Live Terminal SVG

on:
  schedule:
    # Runs every hour
    - cron: "0 * * * *"
  workflow_dispatch:

# Add this permissions block
permissions:
  contents: write

jobs:
  update-svg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run updater script
        run: node update-terminal.js
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: update live terminal SVG"
          file_pattern: live_terminal.svg